import express, { Request, Response } from 'express';
import axios from 'axios';
import { storage } from './storage';
import { credentialManager } from '../core/config/credential-manager';

interface JiraConfig {
  baseUrl: string;
  username: string;
  apiToken: string;
  projectKey: string;
}

interface JiraTask {
  id: string;
  key: string;
  summary: string;
  description?: string;
  status: {
    name: string;
    category: string;
  };
  priority: {
    name: string;
    iconUrl?: string;
  };
  assignee?: {
    displayName: string;
    emailAddress: string;
  };
  reporter: {
    displayName: string;
    emailAddress: string;
  };
  created: string;
  updated: string;
  dueDate?: string;
  project: {
    key: string;
    name: string;
  };
  issueType: {
    name: string;
    iconUrl?: string;
  };
  url: string;
}

// Jira configuration loaded from credentials.json via credentialManager
let jiraConfig: JiraConfig | null = null;

// Initialize Jira config from credential manager
async function initJiraConfig(): Promise<void> {
  try {
    console.log('[Jira API] Loading configuration from credentials.json...');
    const config = await credentialManager.getJiraCredentials();
    
    console.log('[Jira API] Raw config received:', {
      base_url: config.base_url,
      email: config.email,
      api_token: config.api_token ? 'PRESENT' : 'MISSING',
      project_key: config.project_key
    });
    
    jiraConfig = {
      baseUrl: config.base_url,
      username: config.email, // using email as username for Jira
      apiToken: config.api_token,
      projectKey: config.project_key || 'XSX', // Use project_key from JSON
      parentTask: config.parent_task || 'XSX-4113' // Add parent task support
    };
    
    console.log('[Jira API] Configuration loaded successfully:', {
      baseUrl: jiraConfig.baseUrl,
      username: jiraConfig.username,
      apiToken: jiraConfig.apiToken ? 'PRESENT' : 'MISSING',
      projectKey: jiraConfig.projectKey
    });
  } catch (error) {
    console.error('[Jira API] Failed to load configuration:', error);
    jiraConfig = null;
  }
}
const cachedTasks: JiraTask[] = [];
let lastUpdateTime: string = '';
let pollingInterval: NodeJS.Timeout | null = null;

// Comment watcher system
interface CommentWatcher {
  ticketKey: string;
  sessionId: string;
  agentCommentId: string;
  lastChecked: Date;
  isActive: boolean;
}

const activeCommentWatchers: Map<string, CommentWatcher> = new Map();

// Comment watcher functions
async function checkForNewComments(watcher: CommentWatcher): Promise<boolean> {
  try {
    if (!jiraConfig) return false;
    
    const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
    
    // Get ticket comments
    const response = await axios.get(`${jiraConfig.baseUrl}/rest/api/2/issue/${watcher.ticketKey}/comment`, {
      headers: {
        'Authorization': `Basic ${auth}`,
        'Accept': 'application/json'
      },
      timeout: 10000
    });

    const comments = response.data.comments || [];
    
    // Special handling for Communication Agent watcher (watches for ANY new human comment)
    if (watcher.agentCommentId === 'COMMUNICATION_WATCH') {
      const newHumanComments = comments.filter((comment: any) => {
        const commentDate = new Date(comment.created);
        const isAfterLastCheck = commentDate > watcher.lastChecked;
        const isNotBot = !comment.body?.includes('🤖') && 
                        !comment.body?.includes('AI-Generated') &&
                        !comment.body?.includes('*Generated by') &&
                        !comment.body?.includes('Mismatch Summary Agent') && 
                        !comment.body?.includes('Field Comparison Analysis');
        return isAfterLastCheck && isNotBot;
      });
      
      if (newHumanComments.length > 0) {
        console.log(`[Communication Watcher] ✅ Found ${newHumanComments.length} new human comments in ${watcher.ticketKey}`);
        newHumanComments.forEach((comment: any, index: number) => {
          console.log(`[New Comment ${index + 1}] Author: ${comment.author.displayName}, Created: ${comment.created}`);
          console.log(`[New Comment ${index + 1}] Body: ${comment.body.substring(0, 100)}...`);
        });
        return true;
      }
      return false;
    }
    
    // Original logic for Quality Assurance Agent watcher (watches for comments AFTER a specific agent comment)
    const agentCommentIndex = comments.findIndex((comment: any) => comment.id === watcher.agentCommentId);
    
    if (agentCommentIndex === -1) {
      console.log(`[Comment Watcher] Agent comment ${watcher.agentCommentId} not found in ${watcher.ticketKey}`);
      return false;
    }
    
    // Check if there are any comments after our agent comment
    const commentsAfterAgent = comments.slice(agentCommentIndex + 1);
    const newHumanComments = commentsAfterAgent.filter((comment: any) => {
      const commentDate = new Date(comment.created);
      const isAfterLastCheck = commentDate > watcher.lastChecked;
      const isNotBot = !comment.body.includes('Mismatch Summary Agent') && !comment.body.includes('Field Comparison Analysis');
      return isAfterLastCheck && isNotBot;
    });
    
    if (newHumanComments.length > 0) {
      console.log(`[Comment Watcher] Found ${newHumanComments.length} new human comments after agent comment in ${watcher.ticketKey}`);
      
      // Log the new comments for debugging
      newHumanComments.forEach((comment: any, index: number) => {
        console.log(`[New Comment ${index + 1}] Author: ${comment.author.displayName}, Created: ${comment.created}`);
        console.log(`[New Comment ${index + 1}] Body: ${comment.body.substring(0, 100)}...`);
      });
      
      return true;
    }
    
    return false;
  } catch (error: any) {
    console.error(`[Comment Watcher] Error checking comments for ${watcher.ticketKey}:`, error.message);
    return false;
  }
}

// Resume workflow when human response detected
async function resumeWorkflowFromWatcher(sessionId: string, ticketKey: string): Promise<void> {
  try {
    console.log(`[Comment Watcher] Human response detected in ${ticketKey} - resuming workflow ${sessionId}`);
    
    // Import resumeWorkflowAfterHumanResponse function from routes
    const routes = await import('./routes');
    if (routes.resumeWorkflowAfterHumanResponse) {
      await routes.resumeWorkflowAfterHumanResponse(sessionId);
    } else {
      console.error('[Comment Watcher] resumeWorkflowAfterHumanResponse function not found in routes');
    }
    
  } catch (error) {
    console.error(`[Comment Watcher] Error resuming workflow ${sessionId}:`, error);
  }
}


// Auto-polling system for Jira updates and comment watching
function startJiraPolling() {
  if (pollingInterval) {
    clearInterval(pollingInterval);
  }
  
  console.log('Starting Jira auto-polling system every 2 seconds');
  pollingInterval = setInterval(async () => {
    try {
      // Ensure Jira config is loaded before polling
      if (!jiraConfig) {
        await initJiraConfig();
      }
      
      if (!jiraConfig?.username || !jiraConfig?.apiToken) {
        return;
      }
      
      // Re-enabled polling with new token
      
      // Check for new comments on watched tickets
      const watcherEntries = Array.from(activeCommentWatchers.entries());
      for (const [watcherId, watcher] of watcherEntries) {
        if (!watcher.isActive) continue;
        
        const hasNewComments = await checkForNewComments(watcher);
        if (hasNewComments) {
          // Resume workflow and deactivate watcher
          await resumeWorkflowFromWatcher(watcher.sessionId, watcher.ticketKey);
          watcher.isActive = false;
          activeCommentWatchers.delete(watcherId);
        } else {
          // Update last checked time
          watcher.lastChecked = new Date();
        }
      }
      
      const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
      let jql = 'parent = "XSX-4113" ORDER BY updated DESC';
      
      const response = await axios.get(`${jiraConfig.baseUrl}/rest/api/3/search/jql`, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json',
        },
        params: {
          jql,
          fields: 'summary,description,status,priority,reporter,created,updated,duedate,project,issuetype,parent',
          maxResults: 50
        }
      });

      const tasks = response.data.issues.map((issue: any) => ({
        id: issue.id,
        key: issue.key,
        summary: issue.fields.summary || '',
        description: issue.fields.description || '',
        status: {
          name: issue.fields.status?.name || 'Unknown',
          category: issue.fields.status?.statusCategory?.name || 'To Do'
        },
        priority: {
          name: issue.fields.priority?.name || 'Medium',
          iconUrl: issue.fields.priority?.iconUrl || ''
        },
        reporter: {
          displayName: issue.fields.reporter?.displayName || 'Unknown',
          emailAddress: issue.fields.reporter?.emailAddress || ''
        },
        created: issue.fields.created,
        updated: issue.fields.updated,
        dueDate: issue.fields.duedate,
        project: {
          key: issue.fields.project?.key || '',
          name: issue.fields.project?.name || ''
        },
        issueType: {
          name: issue.fields.issuetype?.name || '',
          iconUrl: issue.fields.issuetype?.iconUrl || ''
        },
        parent: issue.fields.parent ? {
          key: issue.fields.parent.key,
          summary: issue.fields.parent.fields?.summary || ''
        } : null,
        url: `${jiraConfig?.baseUrl || 'https://digitalfx.atlassian.net'}/browse/${issue.key}`
      }));

      // Check if there are updates
      const latestUpdate = tasks.length > 0 ? tasks[0].updated : '';
      if (latestUpdate !== lastUpdateTime) {
        console.log(`Jira update detected at ${latestUpdate} - refreshing cache`);
        cachedTasks.length = 0;
        cachedTasks.push(...tasks);
        lastUpdateTime = latestUpdate;
      }
      
    } catch (error: any) {
      console.log('Auto-polling error:', error?.response?.data || error?.message || 'Unknown error');
    }
  }, 2000); // Poll every 2 seconds
}

export function registerJiraRoutes(app: express.Express) {
  // Initialize Jira configuration and start auto-polling when routes are registered
  initJiraConfig().then(() => {
    startJiraPolling();
  });
  // Get Jira configuration
  app.get('/api/jira/config', async (req: Request, res: Response) => {
    try {
      res.json(jiraConfig || {
        baseUrl: '',
        username: '',
        apiToken: '',
        projectKey: ''
      });
    } catch (error) {
      console.error('Error fetching Jira config:', error);
      res.status(500).json({ error: 'Failed to fetch Jira configuration' });
    }
  });

  // Save Jira configuration
  app.put('/api/jira/config', async (req: Request, res: Response) => {
    try {
      const { baseUrl, username, apiToken, projectKey } = req.body;
      
      // Validate required fields
      if (!baseUrl || !username || !apiToken) {
        return res.status(400).json({ error: 'Base URL, username, and API token are required' });
      }

      // Save configuration
      jiraConfig = { baseUrl, username, apiToken, projectKey };
      
      res.json({ success: true });
    } catch (error) {
      console.error('Error saving Jira config:', error);
      res.status(500).json({ error: 'Failed to save Jira configuration' });
    }
  });

  // Test specific issue access
  app.get('/api/jira/test-issue/:issueKey', async (req: Request, res: Response) => {
    try {
      if (!jiraConfig) {
        await initJiraConfig();
      }
      
      if (!jiraConfig) {
        return res.status(400).json({ error: 'Jira configuration not found' });
      }

      const { issueKey } = req.params;
      const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
      
      const response = await axios.get(`${jiraConfig.baseUrl}/rest/api/2/issue/${issueKey}`, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json'
        },
        timeout: 10000
      });

      res.json({
        success: true,
        issue: {
          key: response.data.key,
          summary: response.data.fields.summary,
          status: response.data.fields.status.name,
          project: response.data.fields.project.key
        }
      });
    } catch (error: any) {
      console.error('Error testing issue access:', error?.response?.data || error.message);
      res.status(400).json({
        success: false,
        error: error?.response?.data?.errorMessages || [error.message]
      });
    }
  });

  // Test Jira connection
  app.post('/api/jira/test-connection', async (req: Request, res: Response) => {
    try {
      const { baseUrl, username, apiToken, projectKey } = req.body;
      
      console.log(`Testing connection for user: ${username} at ${baseUrl}`);
      
      if (!baseUrl || !username || !apiToken) {
        return res.status(400).json({ error: 'Base URL, username, and API token are required' });
      }

      const auth = Buffer.from(`${username}:${apiToken}`).toString('base64');
      
      const response = await axios.get(`${baseUrl}/rest/api/2/myself`, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json'
        },
        timeout: 15000
      });

      console.log('Jira connection successful for:', response.data.displayName);
      
      res.json({ 
        success: true, 
        user: response.data.displayName,
        message: 'Connection successful',
        accountId: response.data.accountId
      });
    } catch (error: any) {
      console.error('Jira connection failed:', {
        status: error?.response?.status,
        statusText: error?.response?.statusText,
        data: error?.response?.data,
        message: error.message
      });
      
      let errorMessage = 'Connection failed';
      let errorDetails = error.message;
      
      if (error?.response?.status === 401) {
        errorMessage = 'Authentication failed';
        errorDetails = 'Invalid email address or API token. Please verify your credentials.';
      } else if (error?.response?.status === 403) {
        errorMessage = 'Access denied';
        errorDetails = 'Your account does not have permission to access this Jira instance.';
      } else if (error?.response?.data?.errorMessages) {
        errorDetails = error.response.data.errorMessages.join(', ');
      }
      
      res.status(error?.response?.status || 500).json({ 
        error: errorMessage,
        details: errorDetails
      });
    }
  });

  // Get all projects first
  app.get('/api/jira/projects', async (req: Request, res: Response) => {
    try {
      if (!jiraConfig) {
        return res.status(400).json({ error: 'Jira configuration not found' });
      }

      const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
      
      const response = await axios.get(`${jiraConfig.baseUrl}/rest/api/2/project`, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json'
        },
        timeout: 10000
      });

      res.json(response.data);
    } catch (error: any) {
      console.error('Error fetching Jira projects:', error?.response?.data || error.message);
      res.status(500).json({ 
        error: 'Failed to fetch projects',
        details: error?.response?.data?.errorMessages || error.message
      });
    }
  });

  // Get Jira tasks - returns cached data updated by auto-polling
  app.get('/api/jira/tasks', async (req: Request, res: Response) => {
    try {
      // Ensure Jira config is loaded
      if (!jiraConfig) {
        await initJiraConfig();
      }
      
      if (!jiraConfig) {
        return res.status(400).json({ error: 'Jira configuration not found' });
      }

      // If cache is empty, fetch initial data
      if (cachedTasks.length === 0) {
        const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
        
        // Build JQL query - show subtasks under XSX-4113
        let jql = 'parent = "XSX-4113" ORDER BY updated DESC';
        console.log('Initial fetch for subtasks of parent task: XSX-4113');

        const response = await axios.get(`${jiraConfig.baseUrl}/rest/api/3/search/jql`, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json'
        },
        params: {
          jql: jql,
          maxResults: 50,
          fields: 'summary,description,status,priority,assignee,reporter,created,updated,duedate,project,issuetype'
        },
        timeout: 15000
      });

      const tasks: JiraTask[] = response.data.issues.map((issue: any) => ({
        id: issue.id,
        key: issue.key,
        summary: issue.fields.summary,
        description: issue.fields.description || '',
        status: {
          name: issue.fields.status.name,
          category: issue.fields.status.statusCategory.name
        },
        priority: {
          name: issue.fields.priority?.name || 'Medium',
          iconUrl: issue.fields.priority?.iconUrl
        },
        assignee: issue.fields.assignee ? {
          displayName: issue.fields.assignee.displayName,
          emailAddress: issue.fields.assignee.emailAddress
        } : undefined,
        reporter: {
          displayName: issue.fields.reporter.displayName,
          emailAddress: issue.fields.reporter.emailAddress
        },
        created: issue.fields.created,
        updated: issue.fields.updated,
        dueDate: issue.fields.duedate,
        project: {
          key: issue.fields.project.key,
          name: issue.fields.project.name
        },
        issueType: {
          name: issue.fields.issuetype.name,
          iconUrl: issue.fields.issuetype.iconUrl
        },
        url: `${jiraConfig?.baseUrl || 'https://digitalfx.atlassian.net'}/browse/${issue.key}`
      }));

        // Cache tasks for later use
        cachedTasks.length = 0;
        cachedTasks.push(...tasks);
        lastUpdateTime = tasks.length > 0 ? tasks[0].updated : '';
      }

      res.json(cachedTasks);
    } catch (error: any) {
      console.error('Error fetching Jira tasks:', error?.response?.data || error.message);
      res.status(500).json({ 
        error: 'Failed to fetch tasks',
        details: error?.response?.data?.errorMessages || error.message
      });
    }
  });

  // Sync/refresh tasks
  app.post('/api/jira/sync', async (req: Request, res: Response) => {
    try {
      if (!jiraConfig) {
        return res.status(400).json({ error: 'Jira configuration not found' });
      }

      // This endpoint triggers a fresh fetch of tasks
      // In a real implementation, you might want to update specific tasks or sync with a webhook
      console.log('Syncing Jira tasks...');
      
      res.json({ 
        success: true, 
        message: 'Task sync initiated',
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      console.error('Error syncing Jira tasks:', error);
      res.status(500).json({ error: 'Failed to sync tasks' });
    }
  });

  // Create a new Jira task (optional)
  app.post('/api/jira/tasks', async (req: Request, res: Response) => {
    try {
      if (!jiraConfig) {
        return res.status(400).json({ error: 'Jira configuration not found' });
      }

      const { summary, description, issueType = 'Task', priority = 'Medium' } = req.body;

      if (!summary) {
        return res.status(400).json({ error: 'Summary is required' });
      }

      const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
      
      const createData = {
        fields: {
          project: { key: jiraConfig.projectKey },
          summary: summary,
          description: description || '',
          issuetype: { name: issueType },
          priority: { name: priority }
        }
      };

      const response = await axios.post(`${jiraConfig.baseUrl}/rest/api/2/issue`, createData, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        timeout: 15000
      });

      res.json({
        success: true,
        taskKey: response.data.key,
        taskUrl: `${jiraConfig.baseUrl}/browse/${response.data.key}`
      });
    } catch (error: any) {
      console.error('Error creating Jira task:', error?.response?.data || error.message);
      res.status(500).json({ 
        error: 'Failed to create task',
        details: error?.response?.data?.errors || error.message
      });
    }
  });

  // Get individual Jira ticket
  app.get("/api/jira/ticket/:ticketKey", async (req, res) => {
    try {
      const { ticketKey } = req.params;
      
      // Try to get from cached tasks first
      const cachedTask = cachedTasks.find(task => task.key === ticketKey);
      if (cachedTask) {
        return res.json({
          id: cachedTask.id,
          key: cachedTask.key,
          summary: cachedTask.summary,
          description: cachedTask.description,
          status: cachedTask.status.name,
          priority: cachedTask.priority.name,
          assignee: "Unassigned",
          reporter: cachedTask.reporter.displayName,
          created: cachedTask.created,
          updated: cachedTask.updated
        });
      }
      
      return res.status(404).json({ error: "Ticket not found" });
    } catch (error) {
      console.error("Error fetching Jira ticket:", error);
      res.status(500).json({ error: "Failed to fetch ticket" });
    }
  });

  // Jira data extraction endpoint
  app.get("/api/jira/:ticketKey/data-extraction", (req, res) => {
    const { ticketKey } = req.params;
    
    try {
      // Mock data extraction directly in the endpoint
      const mockDataExtraction: Record<string, any[]> = {
        "HIS-90": [
          { ticket_key: "HIS-90", extracted_field: "client_name", field_value: "Maritime Logistics Ltd", confidence_score: 0.95, source_document: "email_attachment.pdf" },
          { ticket_key: "HIS-90", extracted_field: "policy_type", field_value: "Marine Cargo Insurance", confidence_score: 0.92, source_document: "application_form.pdf" },
          { ticket_key: "HIS-90", extracted_field: "coverage_amount", field_value: "£750,000", confidence_score: 0.88, source_document: "financial_statements.pdf" },
          { ticket_key: "HIS-90", extracted_field: "vessel_name", field_value: "MV Ocean Carrier", confidence_score: 0.94, source_document: "bill_of_lading.pdf" },
          { ticket_key: "HIS-90", extracted_field: "cargo_description", field_value: "Electronics and Computer Equipment", confidence_score: 0.91, source_document: "cargo_manifest.pdf" },
          { ticket_key: "HIS-90", extracted_field: "voyage_route", field_value: "Southampton to Hamburg", confidence_score: 0.89, source_document: "voyage_schedule.pdf" },
          { ticket_key: "HIS-90", extracted_field: "departure_date", field_value: "2025-08-15", confidence_score: 0.93, source_document: "shipping_documents.pdf" },
          { ticket_key: "HIS-90", extracted_field: "broker_name", field_value: "Peters Charley", confidence_score: 0.96, source_document: "broker_correspondence.pdf" },
          { ticket_key: "HIS-90", extracted_field: "broker_email", field_value: "james_potter1@ajg.com", confidence_score: 0.97, source_document: "contact_details.pdf" },
          { ticket_key: "HIS-90", extracted_field: "premium_estimate", field_value: "£8,250", confidence_score: 0.85, source_document: "quote_request.pdf" },
          { ticket_key: "HIS-90", extracted_field: "risk_factors", field_value: "High-value cargo, international waters", confidence_score: 0.78, source_document: "risk_assessment.pdf" },
          { ticket_key: "HIS-90", extracted_field: "previous_claims", field_value: "None in last 3 years", confidence_score: 0.92, source_document: "claims_history.pdf" }
        ],
        "HIS-88": [
          { ticket_key: "HIS-88", extracted_field: "client_name", field_value: "Oceanview Properties Ltd", confidence_score: 0.94, source_document: "property_application.pdf" },
          { ticket_key: "HIS-88", extracted_field: "property_type", field_value: "Commercial Warehouse", confidence_score: 0.91, source_document: "building_survey.pdf" },
          { ticket_key: "HIS-88", extracted_field: "property_value", field_value: "£2,450,000", confidence_score: 0.89, source_document: "valuation_report.pdf" },
          { ticket_key: "HIS-88", extracted_field: "location_address", field_value: "45 Industrial Estate, Portsmouth PO1 2AB", confidence_score: 0.93, source_document: "property_details.pdf" },
          { ticket_key: "HIS-88", extracted_field: "construction_type", field_value: "Steel frame with concrete panels", confidence_score: 0.87, source_document: "structural_report.pdf" },
          { ticket_key: "HIS-88", extracted_field: "occupancy_type", field_value: "Storage and Distribution", confidence_score: 0.92, source_document: "business_operations.pdf" }
        ],
        "HIS-87": [
          { ticket_key: "HIS-87", extracted_field: "slip_reference", field_value: "SLP-2025-001", confidence_score: 0.96, source_document: "lloyd_slip.pdf" },
          { ticket_key: "HIS-87", extracted_field: "syndicate_number", field_value: "2987", confidence_score: 0.94, source_document: "syndicate_details.pdf" },
          { ticket_key: "HIS-87", extracted_field: "lead_underwriter", field_value: "Thompson Marine Underwriters", confidence_score: 0.92, source_document: "underwriter_info.pdf" },
          { ticket_key: "HIS-87", extracted_field: "coverage_type", field_value: "Hull and Machinery", confidence_score: 0.93, source_document: "policy_schedule.pdf" },
          { ticket_key: "HIS-87", extracted_field: "insured_vessel", field_value: "MV Atlantic Pioneer", confidence_score: 0.95, source_document: "vessel_documentation.pdf" },
          { ticket_key: "HIS-87", extracted_field: "vessel_value", field_value: "£15,500,000", confidence_score: 0.91, source_document: "marine_survey.pdf" }
        ]
      };

      const extractedData = mockDataExtraction[ticketKey] || [];
      
      if (extractedData.length === 0) {
        return res.status(404).json({ error: `No data extraction found for ticket: ${ticketKey}` });
      }
      
      res.json(extractedData);
    } catch (error) {
      console.error('Error fetching Jira data extraction:', error);
      res.status(500).json({ error: 'Failed to fetch data extraction' });
    }
  });

  // Post comment to Jira ticket - CRITICAL for Mismatch Summary Agent
  app.post('/api/jira/comment', async (req: Request, res: Response) => {
    try {
      const { ticketKey, comment } = req.body;
      
      if (!ticketKey || !comment) {
        return res.status(400).json({ error: 'ticketKey and comment are required' });
      }
      
      if (!jiraConfig) {
        return res.status(400).json({ error: 'Jira configuration not found' });
      }

      const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
      
      console.log(`[Jira Comment] Posting comment to ticket ${ticketKey}`);
      
      const commentData = {
        body: comment
      };

      const response = await axios.post(`${jiraConfig.baseUrl}/rest/api/2/issue/${ticketKey}/comment`, commentData, {
        headers: {
          'Authorization': `Basic ${auth}`,
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        timeout: 15000
      });

      console.log(`[Jira Success] Comment posted to ${ticketKey} with ID: ${response.data.id}`);
      
      res.json({
        success: true,
        id: response.data.id,
        ticketKey: ticketKey,
        message: 'Comment posted successfully'
      });
    } catch (error: any) {
      console.error(`[Jira Error] Failed to post comment to ${req.body.ticketKey}:`, error?.response?.data || error.message);
      res.status(500).json({ 
        error: 'Failed to post comment',
        details: error?.response?.data?.errorMessages || error.message
      });
    }
  });

  // Function to register a comment watcher after Mismatch Summary Agent posts
  function registerCommentWatcher(ticketKey: string, sessionId: string, agentCommentId: string) {
    const watcherId = `${ticketKey}-${sessionId}`;
    const watcher: CommentWatcher = {
      ticketKey,
      sessionId,
      agentCommentId,
      lastChecked: new Date(),
      isActive: true
    };
    
    activeCommentWatchers.set(watcherId, watcher);
    console.log(`[Comment Watcher] Registered watcher for ticket ${ticketKey}, session ${sessionId}, comment ${agentCommentId}`);
    
    // Log active watchers count
    const activeCount = Array.from(activeCommentWatchers.values()).filter(w => w.isActive).length;
    console.log(`[Comment Watcher] Total active watchers: ${activeCount}`);
  }

  // API endpoint to manually register comment watchers
  app.post('/api/jira/register-watcher', async (req: Request, res: Response) => {
    try {
      const { ticketKey, sessionId, agentCommentId } = req.body;
      
      if (!ticketKey || !sessionId || !agentCommentId) {
        return res.status(400).json({ 
          error: 'Missing required fields: ticketKey, sessionId, agentCommentId' 
        });
      }
      
      registerCommentWatcher(ticketKey, sessionId, agentCommentId);
      
      res.json({ 
        success: true, 
        message: `Comment watcher registered for ${ticketKey}`,
        watcherId: `${ticketKey}-${sessionId}`
      });
    } catch (error: any) {
      console.error('Error registering comment watcher:', error);
      res.status(500).json({ 
        error: 'Failed to register comment watcher',
        details: error.message
      });
    }
  });

  // API endpoint to get active watchers status
  app.get('/api/jira/watchers', async (req: Request, res: Response) => {
    try {
      const watchers = Array.from(activeCommentWatchers.entries()).map(([id, watcher]) => ({
        id,
        ticketKey: watcher.ticketKey,
        sessionId: watcher.sessionId,
        agentCommentId: watcher.agentCommentId,
        lastChecked: watcher.lastChecked,
        isActive: watcher.isActive
      }));
      
      res.json({ 
        success: true, 
        watchers,
        activeCount: watchers.filter(w => w.isActive).length
      });
    } catch (error: any) {
      console.error('Error fetching watchers:', error);
      res.status(500).json({ 
        error: 'Failed to fetch watchers',
        details: error.message
      });
    }
  });

  // Export the registration function for use in other modules
  app.locals.registerCommentWatcher = registerCommentWatcher;

  // Start auto-polling when server starts
  startJiraPolling();
}

// Export registerCommunicationWatcher for use in routes
function registerCommunicationWatcher(ticketKey: string, sessionId: string) {
  const watcherId = `${ticketKey}-${sessionId}-communication`;
  const watcher: CommentWatcher = {
    ticketKey,
    sessionId,
    agentCommentId: 'COMMUNICATION_WATCH', // Special marker - watch for ANY new human comment
    lastChecked: new Date(),
    isActive: true
  };
  
  activeCommentWatchers.set(watcherId, watcher);
  console.log(`[Communication Watcher] ✅ Registered watcher for ticket ${ticketKey}, session ${sessionId}`);
  console.log(`[Communication Watcher] Will automatically resume workflow when ANY new human comment is posted`);
  
  // Log active watchers count
  const activeCount = Array.from(activeCommentWatchers.values()).filter(w => w.isActive).length;
  console.log(`[Comment Watcher] Total active watchers: ${activeCount}`);
}

export { registerCommunicationWatcher };

// Export function to get comments for a specific Jira ticket
export async function getJiraTicketComments(ticketKey: string): Promise<any[]> {
  try {
    if (!jiraConfig) {
      console.error('[getJiraTicketComments] Jira configuration not found');
      return [];
    }
    
    const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
    
    console.log(`[getJiraTicketComments] Fetching comments for ticket ${ticketKey}`);
    
    const response = await axios.get(`${jiraConfig.baseUrl}/rest/api/2/issue/${ticketKey}/comment`, {
      headers: {
        'Authorization': `Basic ${auth}`,
        'Accept': 'application/json'
      },
      timeout: 10000
    });
    
    const comments = response.data.comments || [];
    console.log(`[getJiraTicketComments] Found ${comments.length} comments for ticket ${ticketKey}`);
    
    return comments;
  } catch (error: any) {
    console.error(`[getJiraTicketComments] Error fetching comments for ${ticketKey}:`, error?.response?.data || error.message);
    return [];
  }
}

/**
 * Fetches the list of attachment filenames for a Jira ticket.
 * Tries the real Jira API first; falls back to scanning public/jira-documents/.
 */
export async function getJiraTicketAttachments(ticketKey: string): Promise<string[]> {
  // Try live Jira API
  if (jiraConfig) {
    try {
      const auth = Buffer.from(`${jiraConfig.username}:${jiraConfig.apiToken}`).toString('base64');
      const response = await axios.get(`${jiraConfig.baseUrl}/rest/api/2/issue/${ticketKey}`, {
        headers: { 'Authorization': `Basic ${auth}`, 'Accept': 'application/json' },
        params: { fields: 'attachment' },
        timeout: 8000,
      });
      const attachments: any[] = response.data?.fields?.attachment || [];
      if (attachments.length > 0) {
        console.log(`[getJiraTicketAttachments] Found ${attachments.length} attachment(s) for ${ticketKey} via API`);
        return attachments.map((a: any) => a.filename as string).filter(Boolean);
      }
    } catch (err: any) {
      console.warn(`[getJiraTicketAttachments] API call failed for ${ticketKey}:`, err.message);
    }
  }

  // Fallback: scan local jira-documents directory
  try {
    const { readdirSync, existsSync } = await import('fs');
    const { join } = await import('path');
    const dir = join(process.cwd(), 'public', 'jira-documents');
    if (existsSync(dir)) {
      const files = readdirSync(dir).filter(f =>
        f.endsWith('.pdf') || f.endsWith('.docx') || f.endsWith('.xlsx')
      );
      if (files.length > 0) {
        console.log(`[getJiraTicketAttachments] Fallback: found ${files.length} file(s) in jira-documents`);
        return files;
      }
    }
  } catch (err: any) {
    console.warn('[getJiraTicketAttachments] Filesystem fallback failed:', err.message);
  }

  return [];
}