// CSV Data Lookup Utility - SUBMISSION DATA ONLY (not slips)
export interface CsvSubmissionData {
  submission_id: string;
  token: string;
  broker_ref_hu_number: string;
  intermediary_name: string;
  broker_contact_name: string;
  broker_email: string;
  target_premium: string;
  quote_effective_date: string;
  previous_insurer: string;
  insurance_declined: string;
  convictions: string;
  bankruptcy: string;
  claims_count: string;
  contact_role: string;
  title: string;
  first_name: string;
  middle_name: string;
  surname: string;
  date_of_birth: string;
  occupation: string;
  house_number: string;
  house_name: string;
  address_line1: string;
  city: string;
  postcode: string;
  property_house_number: string;
  property_house_name: string;
  property_address_line1: string;
  property_city: string;
  property_postcode: string;
  cover_type: string;
  building_sums_insured: string;
  content_sums_insured: string;
  total_jewellery_value: string;
  art_collections_value: string;
  solely_occupied: string;
  property_ownership: string;
  property_type: string;
  year_built: string;
  number_of_bedrooms: string;
  listed_building: string;
  roof_construction: string;
  wall_construction: string;
  jewellery_type: string;
  jewellery_description: string;
  jewellery_value: string;
  created_at: string;
  updated_at: string;
  email_subject: string;
}

// CSV data based on actual CSV file
export const csvSubmissionData: CsvSubmissionData[] = [
  {
    submission_id: "UW-2025-001",
    token: "token-abc123",
    broker_ref_hu_number: "REF-HU-2024001",
    intermediary_name: "Arthur J Gallaghar (UK) Ltd",
    broker_contact_name: "Peters Charley",
    broker_email: "james_potter1@ajg.com",
    target_premium: "£8021",
    quote_effective_date: "10/9/24",
    previous_insurer: "Aviva Insurance",
    insurance_declined: "No",
    convictions: "No",
    bankruptcy: "No",
    claims_count: "1",
    contact_role: "Main Policy Holder",
    title: "Ms",
    first_name: "Lee",
    middle_name: "Warner",
    surname: "Jones",
    date_of_birth: "5/19/56",
    occupation: "Director",
    house_number: "122",
    house_name: "Hamilton House",
    address_line1: "Victoria Street",
    city: "Princess Road",
    postcode: "CW5 8JE",
    property_house_number: "122",
    property_house_name: "Hamilton House",
    property_address_line1: "Victoria Street",
    property_city: "Princess Road",
    property_postcode: "CW5 8JE",
    cover_type: "Combined",
    building_sums_insured: "£2230555",
    content_sums_insured: "£291655",
    total_jewellery_value: "£97507",
    art_collections_value: "",
    solely_occupied: "Yes",
    property_ownership: "Owner Occupied",
    property_type: "House - Detached",
    year_built: "1820",
    number_of_bedrooms: "4",
    listed_building: "Grade II Listed",
    roof_construction: "Slate",
    wall_construction: "Stone",
    jewellery_type: "Necklace",
    jewellery_description: "Victorian diamond necklace with sapphires",
    jewellery_value: "£29014",
    created_at: "2024-07-10T09:15:00",
    updated_at: "2024-07-10T09:15:00",
    email_subject: "RE: Home Insurance Quote Request - Lee Warner Jones, Hamilton House, Victoria Street"
  },
  {
    submission_id: "UW-2025-002",
    token: "token-def456",
    broker_ref_hu_number: "REF-HU-2024002",
    intermediary_name: "Aon UK Limited",
    broker_contact_name: "Michael Thompson",
    broker_email: "m.thompson@aon.com",
    target_premium: "£12000",
    quote_effective_date: "7/20/24",
    previous_insurer: "Zurich Insurance",
    insurance_declined: "No",
    convictions: "No",
    bankruptcy: "No",
    claims_count: "0",
    contact_role: "Main Policy Holder",
    title: "Mr",
    first_name: "Michael",
    middle_name: "James",
    surname: "Thompson",
    date_of_birth: "11/8/78",
    occupation: "Insurance Director",
    house_number: "78",
    house_name: "",
    address_line1: "Regent Street",
    city: "London",
    postcode: "W1B 5RL",
    property_house_number: "78",
    property_house_name: "",
    property_address_line1: "Regent Street",
    property_city: "London",
    property_postcode: "W1B 5RL",
    cover_type: "Buildings Only",
    building_sums_insured: "£1200000",
    content_sums_insured: "£0",
    total_jewellery_value: "£120000",
    art_collections_value: "",
    solely_occupied: "Yes",
    property_ownership: "Owner Occupied",
    property_type: "House - Detached",
    year_built: "1820",
    number_of_bedrooms: "6",
    listed_building: "Grade I Listed",
    roof_construction: "Slate",
    wall_construction: "Portland Stone",
    jewellery_type: "Watch",
    jewellery_description: "Vintage Rolex Submariner collection",
    jewellery_value: "£45000",
    created_at: "2024-07-10T10:30:00",
    updated_at: "2024-07-10T10:30:00",
    email_subject: "RE: Commercial Property Insurance Quote - Michael Thompson, Regent Street London"
  },
  {
    submission_id: "UW-2025-003",
    token: "token-ghi789",
    broker_ref_hu_number: "REF-HU-2024003",
    intermediary_name: "Willis Towers Watson",
    broker_contact_name: "Emma Wilson",
    broker_email: "emma.wilson@willistowerswatson.com",
    target_premium: "£6750",
    quote_effective_date: "7/25/24",
    previous_insurer: "Direct Line",
    insurance_declined: "No",
    convictions: "No",
    bankruptcy: "No",
    claims_count: "2",
    contact_role: "Main Policy Holder",
    title: "Mrs",
    first_name: "Emma",
    middle_name: "Louise",
    surname: "Wilson",
    date_of_birth: "7/14/90",
    occupation: "Account Manager",
    house_number: "156",
    house_name: "The Gables",
    address_line1: "Park Avenue",
    city: "Birmingham",
    postcode: "B15 2TH",
    property_house_number: "156",
    property_house_name: "The Gables",
    property_address_line1: "Park Avenue",
    property_city: "Birmingham",
    property_postcode: "B15 2TH",
    cover_type: "Combined",
    building_sums_insured: "£650000",
    content_sums_insured: "£125000",
    total_jewellery_value: "£65000",
    art_collections_value: "£30000",
    solely_occupied: "Yes",
    property_ownership: "Owner Occupied",
    property_type: "Detached House",
    year_built: "1985",
    number_of_bedrooms: "4",
    listed_building: "No",
    roof_construction: "Tile",
    wall_construction: "Brick",
    jewellery_type: "Ring",
    jewellery_description: "Art Deco diamond engagement ring",
    jewellery_value: "£18000",
    created_at: "2024-07-10T11:45:00",
    updated_at: "2024-07-10T11:45:00"
  },
  {
    submission_id: "UW-2025-004",
    token: "token-jkl012",
    broker_ref_hu_number: "REF-HU-2024004",
    intermediary_name: "Gallagher UK",
    broker_contact_name: "David Brown",
    broker_email: "d.brown@ajg.com",
    target_premium: "£9200",
    quote_effective_date: "2024-08-01",
    previous_insurer: "RSA Insurance",
    insurance_declined: "No",
    convictions: "No",
    bankruptcy: "No",
    claims_count: "0",
    contact_role: "Broker",
    title: "Mr",
    first_name: "David",
    middle_name: "Robert",
    surname: "Brown",
    date_of_birth: "1982-05-30",
    occupation: "Senior Account Executive",
    house_number: "23",
    house_name: "Rosewood Court",
    address_line1: "High Street",
    city: "Leeds",
    postcode: "LS1 6ED",
    property_house_number: "23",
    property_house_name: "Rosewood Court",
    property_address_line1: "High Street",
    property_city: "Leeds",
    property_postcode: "LS1 6ED",
    cover_type: "Combined",
    building_sums_insured: "£800000",
    content_sums_insured: "£140000",
    total_jewellery_value: "£95000",
    art_collections_value: "£50000",
    solely_occupied: "Yes",
    property_ownership: "Owner Occupied",
    property_type: "Modern Apartment",
    year_built: "2010",
    number_of_bedrooms: "3",
    listed_building: "No",
    roof_construction: "Flat Roof",
    wall_construction: "Concrete",
    jewellery_type: "Earrings",
    jewellery_description: "Cartier diamond earrings",
    jewellery_value: "£12000",
    created_at: "2024-07-10T12:00:00",
    updated_at: "2024-07-10T12:00:00"
  },
  {
    submission_id: "UW-2025-005",
    token: "token-mno345",
    broker_ref_hu_number: "REF-HU-2024005",
    intermediary_name: "JLT Specialty Limited",
    broker_contact_name: "Rachel Green",
    broker_email: "r.green@jltspecialty.com",
    target_premium: "£15500",
    quote_effective_date: "2024-08-10",
    previous_insurer: "Allianz Insurance",
    insurance_declined: "No",
    convictions: "No",
    bankruptcy: "No",
    claims_count: "1",
    contact_role: "Broker",
    title: "Dr",
    first_name: "Rachel",
    middle_name: "Anne",
    surname: "Green",
    date_of_birth: "1975-12-03",
    occupation: "Risk Management Consultant",
    house_number: "89",
    house_name: "Millfield Manor",
    address_line1: "Church Lane",
    city: "Oxford",
    postcode: "OX1 3ER",
    property_house_number: "89",
    property_house_name: "Millfield Manor",
    property_address_line1: "Church Lane",
    property_city: "Oxford",
    property_postcode: "OX1 3ER",
    cover_type: "Combined",
    building_sums_insured: "£1500000",
    content_sums_insured: "£200000",
    total_jewellery_value: "£150000",
    art_collections_value: "£100000",
    solely_occupied: "Yes",
    property_ownership: "Owner Occupied",
    property_type: "Country Manor",
    year_built: "1750",
    number_of_bedrooms: "8",
    listed_building: "Grade II* Listed",
    roof_construction: "Thatch",
    wall_construction: "Cotswold Stone",
    jewellery_type: "Bracelet",
    jewellery_description: "Antique gold bracelet with emeralds",
    jewellery_value: "£35000",
    created_at: "2024-07-10T13:15:00",
    updated_at: "2024-07-10T13:15:00"
  },
  {
    submission_id: "UW-2025-006",
    token: "token-pqr678",
    broker_ref_hu_number: "REF-HU-2024006",
    intermediary_name: "Howden Broking Group",
    broker_contact_name: "James Miller",
    broker_email: "j.miller@howdengroup.com",
    target_premium: "£7800",
    quote_effective_date: "2024-08-15",
    previous_insurer: "AXA Insurance",
    insurance_declined: "No",
    convictions: "No",
    bankruptcy: "No",
    claims_count: "0",
    contact_role: "Broker",
    title: "Mr",
    first_name: "James",
    middle_name: "William",
    surname: "Miller",
    date_of_birth: "1987-09-17",
    occupation: "Account Handler",
    house_number: "12",
    house_name: "Riverside Gardens",
    address_line1: "Mill Lane",
    city: "Bristol",
    postcode: "BS1 2QR",
    property_house_number: "12",
    property_house_name: "Riverside Gardens",
    property_address_line1: "Mill Lane",
    property_city: "Bristol",
    property_postcode: "BS1 2QR",
    cover_type: "Combined",
    building_sums_insured: "£700000",
    content_sums_insured: "£130000",
    total_jewellery_value: "£75000",
    art_collections_value: "£35000",
    solely_occupied: "Yes",
    property_ownership: "Owner Occupied",
    property_type: "Converted Warehouse",
    year_built: "1920",
    number_of_bedrooms: "4",
    listed_building: "No",
    roof_construction: "Metal Sheeting",
    wall_construction: "Brick",
    jewellery_type: "Brooch",
    jewellery_description: "Edwardian pearl brooch",
    jewellery_value: "£8500",
    created_at: "2024-07-10T14:20:00",
    updated_at: "2024-07-10T14:20:00"
  },
  {
    submission_id: "UW-2025-007",
    token: "token-stu901",
    broker_ref_hu_number: "REF-HU-2024007",
    intermediary_name: "Lockton Companies",
    broker_contact_name: "Sophie Davis",
    broker_email: "s.davis@lockton.com",
    target_premium: "£11200",
    quote_effective_date: "2024-08-20",
    previous_insurer: "Ecclesiastical Insurance",
    insurance_declined: "No",
    convictions: "No",
    bankruptcy: "No",
    claims_count: "1",
    contact_role: "Broker",
    title: "Miss",
    first_name: "Sophie",
    middle_name: "Grace",
    surname: "Davis",
    date_of_birth: "1992-01-25",
    occupation: "Assistant Account Manager",
    house_number: "67",
    house_name: "Hawthorn Cottage",
    address_line1: "Village Green",
    city: "Cotswolds",
    postcode: "GL54 1HN",
    property_house_number: "67",
    property_house_name: "Hawthorn Cottage",
    property_address_line1: "Village Green",
    property_city: "Cotswolds",
    property_postcode: "GL54 1HN",
    cover_type: "Combined",
    building_sums_insured: "£950000",
    content_sums_insured: "£175000",
    total_jewellery_value: "£110000",
    art_collections_value: "£60000",
    solely_occupied: "Yes",
    property_ownership: "Owner Occupied",
    property_type: "Thatched Cottage",
    year_built: "1650",
    number_of_bedrooms: "5",
    listed_building: "Grade II Listed",
    roof_construction: "Thatch",
    wall_construction: "Cotswold Stone",
    jewellery_type: "Pendant",
    jewellery_description: "Georgian diamond pendant",
    jewellery_value: "£22000",
    created_at: "2024-07-10T15:35:00",
    updated_at: "2024-07-10T15:35:00"
  }
];

// Utility function to get submission data by ID
export function getSubmissionDataById(submissionId: string): CsvSubmissionData | null {
  return csvSubmissionData.find(data => data.submission_id === submissionId) || null;
}

// Utility function to get all available submission IDs
export function getAvailableSubmissionIds(): string[] {
  return csvSubmissionData.map(data => data.submission_id);
}